# Generated by Django 6.0.7 on 2026-08-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReDispersalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redispersal_requests', to='livestock.animal')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_new_beneficiary', models.ForeignKey(blank=True, help_text='May be decided later if not yet identified.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.beneficiary')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('INITIAL_DISPERSAL', 'Initial Dispersal'), ('RE_DISPERSAL', 'Re-Dispersal')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (current custody)'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='NULL = currently active custody. Set when animal is transferred/returned.', null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude where the animal was delivered to this beneficiary.', max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude where the animal was delivered to this beneficiary.', max_digits=9, null=True)),
                ('end_remarks', models.TextField(blank=True, default='', help_text='Free-text notes about why custody ended.')),
                ('condition_at_transfer', models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('INJURED', 'Injured'), ('PREGNANT', 'Pregnant'), ('DECEASED', 'Deceased')], default='HEALTHY', max_length=20)),
                ('offspring_count_returned', models.PositiveIntegerField(default=0, help_text='How many offspring this beneficiary returned to CVO (for pass-on obligation tracking).')),
                ('contract_document', models.FileField(blank=True, help_text='Signed dispersal agreement / MOA PDF.', null=True, upload_to='dispersal/contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_records', to='livestock.animal')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_records', to='beneficiaries.beneficiary')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_dispersals', to=settings.AUTH_USER_MODEL)),
                ('end_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_records', to='dispersal.transferreason')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('animal',), name='unique_active_ownership_per_animal')],
            },
        ),
    ]
