# Generated by Django 6.0.7 on 2026-08-27 06:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_privacy_consent_date_and_more'),
        ('dispersal', '0001_initial'),
        ('livestock', '0002_historicalanimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOwnershipRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('INITIAL_DISPERSAL', 'Initial Dispersal'), ('RE_DISPERSAL', 'Re-Dispersal')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (current custody)'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='NULL = currently active custody. Set when animal is transferred/returned.', null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude where the animal was delivered to this beneficiary.', max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude where the animal was delivered to this beneficiary.', max_digits=9, null=True)),
                ('end_remarks', models.TextField(blank=True, default='', help_text='Free-text notes about why custody ended.')),
                ('condition_at_transfer', models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('INJURED', 'Injured'), ('PREGNANT', 'Pregnant'), ('DECEASED', 'Deceased')], default='HEALTHY', max_length=20)),
                ('offspring_count_returned', models.PositiveIntegerField(default=0, help_text='How many offspring this beneficiary returned to CVO (for pass-on obligation tracking).')),
                ('contract_document', models.TextField(blank=True, help_text='Signed dispersal agreement / MOA PDF.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.animal')),
                ('beneficiary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiaries.beneficiary')),
                ('end_reason', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispersal.transferreason')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ownership record',
                'verbose_name_plural': 'historical ownership records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
