# Generated by Django 6.0.7 on 2026-08-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city_municipality', models.CharField(max_length=200)),
                ('boundary_geojson', models.JSONField(blank=True, help_text='Optional GeoJSON polygon for choropleth/boundary overlay on the map.', null=True)),
            ],
            options={
                'ordering': ['city_municipality', 'name'],
                'unique_together': {('name', 'city_municipality')},
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sitio_purok', models.CharField(blank=True, default='', max_length=200)),
                ('full_address', models.TextField(blank=True, default='')),
                ('valid_id_type', models.CharField(blank=True, default='', help_text="e.g., PhilSys ID, Voter's ID, Barangay Certificate", max_length=50)),
                ('valid_id_number', models.CharField(blank=True, default='', max_length=100)),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='beneficiaries/ids/')),
                ('household_head', models.BooleanField(default=False, help_text='Is this person the household head?')),
                ('livelihood_type', models.CharField(blank=True, default='', help_text='Primary livelihood: farming, livestock, fishing, etc.', max_length=100)),
                ('is_active_beneficiary', models.BooleanField(default=True, help_text='Can they currently receive/hold animals? Set False for inactive.')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Beneficiary's default farm/home latitude.", max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text="Beneficiary's default farm/home longitude.", max_digits=9, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='beneficiaries.barangay')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
