# Generated by Django 6.0.7 on 2026-08-27 06:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='privacy_consent_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when privacy consent was obtained.', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='privacy_consent_given',
            field=models.BooleanField(default=False, help_text='Beneficiary has been informed of and consented to data collection as required by the Philippine Data Privacy Act of 2012 (RA 10173).'),
        ),
        migrations.CreateModel(
            name='HistoricalBeneficiary',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sitio_purok', models.CharField(blank=True, default='', max_length=200)),
                ('full_address', models.TextField(blank=True, default='')),
                ('valid_id_type', models.CharField(blank=True, default='', help_text="e.g., PhilSys ID, Voter's ID, Barangay Certificate", max_length=50)),
                ('valid_id_number', models.CharField(blank=True, default='', max_length=100)),
                ('id_image', models.TextField(blank=True, max_length=100, null=True)),
                ('household_head', models.BooleanField(default=False, help_text='Is this person the household head?')),
                ('livelihood_type', models.CharField(blank=True, default='', help_text='Primary livelihood: farming, livestock, fishing, etc.', max_length=100)),
                ('is_active_beneficiary', models.BooleanField(default=True, help_text='Can they currently receive/hold animals? Set False for inactive.')),
                ('date_registered', models.DateField(blank=True, editable=False)),
                ('privacy_consent_given', models.BooleanField(default=False, help_text='Beneficiary has been informed of and consented to data collection as required by the Philippine Data Privacy Act of 2012 (RA 10173).')),
                ('privacy_consent_date', models.DateTimeField(blank=True, help_text='Timestamp when privacy consent was obtained.', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Beneficiary's default farm/home latitude.", max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text="Beneficiary's default farm/home longitude.", max_digits=9, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('barangay', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiaries.barangay')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical beneficiary',
                'verbose_name_plural': 'historical beneficiarys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
