# Generated by Django 6.0.7 on 2026-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('OFFICER', 'CVO Veterinarian / Officer (Encoder)'), ('SUPERVISOR', 'CVO Supervisor'), ('COORDINATOR', 'Barangay Coordinator'), ('STAFF', 'Staff (Read-Only)')], default='OFFICER', max_length=20),
        ),
    ]
