# Generated by Django 6.0.7 on 2026-08-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['species', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('LIVESTOCK', 'Livestock'), ('POULTRY', 'Poultry')], default='LIVESTOCK', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(editable=False, help_text='Auto-generated unique tag: CVO-{SPECIES}-{YEAR}-{SEQ}', max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('estimated_age_months', models.PositiveIntegerField(blank=True, help_text='Used when birth date is unknown.', null=True)),
                ('color_markings', models.CharField(blank=True, default='', max_length=200)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/photos/')),
                ('is_batch', models.BooleanField(default=False, help_text='True if this record represents a batch/lot (e.g., 50 chicks) rather than a single animal.')),
                ('batch_quantity', models.PositiveIntegerField(default=1, help_text='Number of animals in this batch. Always 1 for individually-tagged animals.')),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available (in CVO custody)'), ('DISPERSED', 'Currently Dispersed'), ('UNDER_RE_DISPERSAL_REVIEW', 'Under Re-Dispersal Review'), ('RETURNED_TO_CVO', 'Returned to CVO'), ('DECEASED', 'Deceased'), ('CULLED', 'Culled'), ('SOLD_WITH_APPROVAL', 'Sold with Approval')], default='AVAILABLE', max_length=30)),
                ('date_acquired_by_cvo', models.DateField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', help_text='Origin: DA-RFO donation, LGU-purchased, confiscated, etc.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('current_owner', models.ForeignKey(blank=True, help_text='Who currently holds this animal. Null = in CVO custody/not yet dispersed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_animals', to='beneficiaries.beneficiary')),
                ('parent_batch', models.ForeignKey(blank=True, help_text='If this record was split from a larger batch, reference the original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_batches', to='livestock.animal')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='livestock.breed')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='livestock.species')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('DEWORMING', 'Deworming'), ('TREATMENT', 'Treatment'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='animals/health/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.animal')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='livestock.species'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'name')},
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tag_id'], name='livestock_a_tag_id_4defc8_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['current_status'], name='livestock_a_current_9539c2_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species', 'current_status'], name='livestock_a_species_7f102d_idx'),
        ),
    ]
