# Generated by Django 6.0.7 on 2026-08-27 06:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_privacy_consent_date_and_more'),
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnimal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tag_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated unique tag: CVO-{SPECIES}-{YEAR}-{SEQ}', max_length=50)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('estimated_age_months', models.PositiveIntegerField(blank=True, help_text='Used when birth date is unknown.', null=True)),
                ('color_markings', models.CharField(blank=True, default='', max_length=200)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('is_batch', models.BooleanField(default=False, help_text='True if this record represents a batch/lot (e.g., 50 chicks) rather than a single animal.')),
                ('batch_quantity', models.PositiveIntegerField(default=1, help_text='Number of animals in this batch. Always 1 for individually-tagged animals.')),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available (in CVO custody)'), ('DISPERSED', 'Currently Dispersed'), ('UNDER_RE_DISPERSAL_REVIEW', 'Under Re-Dispersal Review'), ('RETURNED_TO_CVO', 'Returned to CVO'), ('DECEASED', 'Deceased'), ('CULLED', 'Culled'), ('SOLD_WITH_APPROVAL', 'Sold with Approval')], default='AVAILABLE', max_length=30)),
                ('date_acquired_by_cvo', models.DateField(blank=True, editable=False)),
                ('source', models.CharField(blank=True, default='', help_text='Origin: DA-RFO donation, LGU-purchased, confiscated, etc.', max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('breed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.breed')),
                ('current_owner', models.ForeignKey(blank=True, db_constraint=False, help_text='Who currently holds this animal. Null = in CVO custody/not yet dispersed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiaries.beneficiary')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_batch', models.ForeignKey(blank=True, db_constraint=False, help_text='If this record was split from a larger batch, reference the original.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.animal')),
                ('species', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.species')),
            ],
            options={
                'verbose_name': 'historical animal',
                'verbose_name_plural': 'historical animals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
