# Generated by Django 6.0.7 on 2026-08-27 09:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_privacy_consent_date_and_more'),
        ('livestock', '0002_historicalanimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOffspring',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('child_tag_id', models.CharField(blank=True, default='', help_text='Tag ID if child is registered; otherwise descriptive label.', max_length=50)),
                ('child_sex', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=6)),
                ('birth_date', models.DateField()),
                ('litter_size', models.PositiveIntegerField(default=1, help_text='Number of offspring in this birth event.')),
                ('status', models.CharField(choices=[('BORN', 'Born'), ('RETURNED_TO_CVO', 'Returned to CVO'), ('REMAINING', 'Remaining with Beneficiary'), ('DECEASED', 'Deceased')], default='BORN', max_length=20)),
                ('returned_to_cvo_date', models.DateField(blank=True, help_text='Date when this offspring was returned to CVO.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('child', models.ForeignKey(blank=True, db_constraint=False, help_text='The child animal record (if registered in the system).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.animal')),
                ('child_species', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.species')),
                ('dam', models.ForeignKey(blank=True, db_constraint=False, help_text='The mother animal.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.animal')),
                ('held_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Beneficiary currently holding this offspring.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiaries.beneficiary')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical offspring',
                'verbose_name_plural': 'historical offsprings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Offspring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_tag_id', models.CharField(blank=True, default='', help_text='Tag ID if child is registered; otherwise descriptive label.', max_length=50)),
                ('child_sex', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=6)),
                ('birth_date', models.DateField()),
                ('litter_size', models.PositiveIntegerField(default=1, help_text='Number of offspring in this birth event.')),
                ('status', models.CharField(choices=[('BORN', 'Born'), ('RETURNED_TO_CVO', 'Returned to CVO'), ('REMAINING', 'Remaining with Beneficiary'), ('DECEASED', 'Deceased')], default='BORN', max_length=20)),
                ('returned_to_cvo_date', models.DateField(blank=True, help_text='Date when this offspring was returned to CVO.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('child', models.ForeignKey(blank=True, help_text='The child animal record (if registered in the system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_child', to='livestock.animal')),
                ('child_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_records', to='livestock.species')),
                ('dam', models.ForeignKey(help_text='The mother animal.', on_delete=django.db.models.deletion.CASCADE, related_name='offspring_as_dam', to='livestock.animal')),
                ('held_by', models.ForeignKey(blank=True, help_text='Beneficiary currently holding this offspring.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_offspring', to='beneficiaries.beneficiary')),
            ],
            options={
                'ordering': ['-birth_date', '-created_at'],
                'indexes': [models.Index(fields=['dam', 'status'], name='livestock_o_dam_id_aa66b3_idx'), models.Index(fields=['birth_date'], name='livestock_o_birth_d_b50e88_idx')],
            },
        ),
    ]
