# Generated by Django 6.0.7 on 2026-08-27 09:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0002_beneficiary_privacy_consent_date_and_more'),
        ('livestock', '0002_historicalanimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHealthEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('DEWORMING', 'Deworming'), ('TREATMENT', 'Treatment'), ('INSPECTION', 'Inspection'), ('ILLNESS', 'Illness Report'), ('DISEASE_SUSPECT', 'Disease Suspect Report'), ('MORTALITY', 'Mortality')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', help_text='Severity level for illness/disease-suspect events.', max_length=10)),
                ('event_date', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude where the event was observed.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude where the event was observed.', max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.TextField(blank=True, help_text='Photo evidence of the health event.', max_length=100, null=True)),
                ('report_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], default='SUBMITTED', help_text='Status of disease-suspect reports (for review workflow).', max_length=15)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.animal')),
                ('disease_suspected', models.ForeignKey(blank=True, db_constraint=False, help_text='Required when event_type is DISEASE_SUSPECT.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='health.diseasetype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical health event',
                'verbose_name_plural': 'historical health events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuarantineZone',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g., 'Bayawan Zone 1 - ASF Response'.", max_length=200)),
                ('boundary_geojson', models.JSONField(blank=True, help_text="Custom GeoJSON polygon. If null, uses the linked barangay's boundary.", null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = zone is open-ended (no planned end date).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive zones are historical records, not enforced.')),
                ('is_blocking', models.BooleanField(default=True, help_text='If true, dispersal/re-dispersal to/from this zone is blocked. If false, a warning is shown but the transfer is allowed.')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional context: reason for quarantine, DA directives, etc.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('barangay', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiaries.barangay')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disease_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='health.diseasetype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical quarantine zone',
                'verbose_name_plural': 'historical quarantine zones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='QuarantineZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g., 'Bayawan Zone 1 - ASF Response'.", max_length=200)),
                ('boundary_geojson', models.JSONField(blank=True, help_text="Custom GeoJSON polygon. If null, uses the linked barangay's boundary.", null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = zone is open-ended (no planned end date).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive zones are historical records, not enforced.')),
                ('is_blocking', models.BooleanField(default=True, help_text='If true, dispersal/re-dispersal to/from this zone is blocked. If false, a warning is shown but the transfer is allowed.')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional context: reason for quarantine, DA directives, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_zones', to='beneficiaries.barangay')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_zones_created', to=settings.AUTH_USER_MODEL)),
                ('disease_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_zones', to='health.diseasetype')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('DEWORMING', 'Deworming'), ('TREATMENT', 'Treatment'), ('INSPECTION', 'Inspection'), ('ILLNESS', 'Illness Report'), ('DISEASE_SUSPECT', 'Disease Suspect Report'), ('MORTALITY', 'Mortality')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', help_text='Severity level for illness/disease-suspect events.', max_length=10)),
                ('event_date', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude where the event was observed.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude where the event was observed.', max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, help_text='Photo evidence of the health event.', null=True, upload_to='health/events/')),
                ('report_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], default='SUBMITTED', help_text='Status of disease-suspect reports (for review workflow).', max_length=15)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='livestock.animal')),
                ('disease_suspected', models.ForeignKey(blank=True, help_text='Required when event_type is DISEASE_SUSPECT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events', to='health.diseasetype')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events_reported', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='health_heal_event_t_685637_idx'), models.Index(fields=['event_date'], name='health_heal_event_d_324a6a_idx'), models.Index(fields=['report_status'], name='health_heal_report__64f689_idx'), models.Index(fields=['animal', 'event_type'], name='health_heal_animal__2306b8_idx')],
            },
        ),
    ]
