# Generated by Django 6.0.7 on 2026-08-27 13:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispersal', '0002_historicalownershiprecord'),
        ('health', '0001_initial'),
        ('livestock', '0003_historicaloffspring_offspring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('QUARANTINE', 'Quarantine Zone'), ('DISEASE_REPORT', 'Disease Report'), ('DISPERSAL_REQUEST', 'Dispersal Request'), ('DISPERSAL_APPROVED', 'Dispersal Approved'), ('DISPERSAL_REJECTED', 'Dispersal Rejected'), ('REDISPERSAL_REQUEST', 'Re-Dispersal Request'), ('REDISPERSAL_APPROVED', 'Re-Dispersal Approved'), ('REDISPERSAL_REJECTED', 'Re-Dispersal Rejected'), ('PASS_ON_DUE', 'Pass-On Due'), ('PASS_ON_OVERDUE', 'Pass-On Overdue'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_health_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='health.healthevent')),
                ('related_offspring', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.offspring')),
                ('related_ownership_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dispersal.ownershiprecord')),
                ('related_quarantine_zone', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='health.quarantinezone')),
            ],
            options={
                'verbose_name': 'historical notification',
                'verbose_name_plural': 'historical notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('QUARANTINE', 'Quarantine Zone'), ('DISEASE_REPORT', 'Disease Report'), ('DISPERSAL_REQUEST', 'Dispersal Request'), ('DISPERSAL_APPROVED', 'Dispersal Approved'), ('DISPERSAL_REJECTED', 'Dispersal Rejected'), ('REDISPERSAL_REQUEST', 'Re-Dispersal Request'), ('REDISPERSAL_APPROVED', 'Re-Dispersal Approved'), ('REDISPERSAL_REJECTED', 'Re-Dispersal Rejected'), ('PASS_ON_DUE', 'Pass-On Due'), ('PASS_ON_OVERDUE', 'Pass-On Overdue'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_health_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='health.healthevent')),
                ('related_offspring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='livestock.offspring')),
                ('related_ownership_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='dispersal.ownershiprecord')),
                ('related_quarantine_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='health.quarantinezone')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'is_archived'], name='notificatio_recipie_b9dbed_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
