# Generated by Django 6.0.7 on 2026-08-26 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('dispersal', '0001_initial'),
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('address_text', models.TextField(blank=True, default='')),
                ('caretaker_type', models.CharField(choices=[('FORMAL_BENEFICIARY', 'Formal Beneficiary'), ('INFORMAL_CARETAKER', 'Informal Caretaker'), ('TEMPORARY_FOSTER', 'Temporary Foster'), ('CVO_HOLDING_FACILITY', 'CVO Holding Facility')], default='FORMAL_BENEFICIARY', max_length=25)),
                ('default_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Default location latitude.', max_digits=9, null=True)),
                ('default_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Default location longitude.', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretakers', to='beneficiaries.barangay')),
                ('beneficiary', models.ForeignKey(blank=True, help_text='Link to formal beneficiary record when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker_profiles', to='beneficiaries.beneficiary')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='GeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_code', models.CharField(editable=False, help_text='Unique human-readable + QR-scannable code, e.g. GT-2026-00456', max_length=30, unique=True)),
                ('tag_type', models.CharField(choices=[('EAR_TAG', 'Ear Tag'), ('LEG_BAND', 'Leg Band'), ('QR_ONLY', 'QR Only'), ('GPS_COLLAR', 'GPS Collar')], default='EAR_TAG', max_length=15)),
                ('date_tagged', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if tag is retired (lost, animal deceased, etc.).')),
                ('last_checkin', models.DateTimeField(blank=True, help_text='Timestamp of most recent LocationCheckIn for any custodianship under this tag.', null=True)),
                ('last_device_ping', models.DateTimeField(blank=True, help_text='Last ping from GPS device — separate from checkin to detect device failures.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.OneToOneField(help_text='The animal this tag is attached to.', on_delete=django.db.models.deletion.PROTECT, related_name='geo_tag', to='livestock.animal')),
                ('replacement_of', models.ForeignKey(blank=True, help_text='If this is a replacement tag, link to the old tag for lineage continuity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='geotagging.geotag')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Custodianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('intake_condition', models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('INJURED', 'Injured'), ('UNDERWEIGHT', 'Underweight')], default='HEALTHY', max_length=15)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exit_condition', models.CharField(blank=True, choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('INJURED', 'Injured'), ('UNDERWEIGHT', 'Underweight'), ('DECEASED', 'Deceased')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodianships', to='geotagging.caretaker')),
                ('linked_dispersal_record', models.ForeignKey(blank=True, help_text='Populated when hand-off was triggered by a formal dispersal/re-dispersal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geotag_custodianships', to='dispersal.ownershiprecord')),
                ('geo_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodianships', to='geotagging.geotag')),
                ('end_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodianships', to='geotagging.handoffreason')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('FIELD_VISIT', 'Field Visit'), ('MANUAL_UPDATE', 'Manual Update'), ('GPS_DEVICE', 'GPS Device'), ('CITIZEN_REPORT', 'Citizen Report')], default='FIELD_VISIT', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='geotagging/checkins/')),
                ('notes', models.TextField(blank=True, default='')),
                ('checked_in_by', models.ForeignKey(blank=True, help_text='Null if from automated GPS device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geotag_checkins', to=settings.AUTH_USER_MODEL)),
                ('custodianship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='geotagging.custodianship')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geotag',
            index=models.Index(fields=['tag_code'], name='geotagging__tag_cod_8515bf_idx'),
        ),
        migrations.AddIndex(
            model_name='geotag',
            index=models.Index(fields=['is_active'], name='geotagging__is_acti_2593dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='custodianship',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('geo_tag',), name='unique_active_custodianship_per_geotag'),
        ),
    ]
