# Generated by Django 6.0.7 on 2026-08-27 06:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotagging', '0001_initial'),
        ('livestock', '0002_historicalanimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcheckin',
            name='gps_accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy radius in meters as reported by the device.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='gps_altitude_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters above WGS84 ellipsoid.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='gps_speed_mps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Speed in meters per second at time of check-in.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True if GPS accuracy exceeded the configured threshold; requires manual review.'),
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='review_reason',
            field=models.CharField(blank=True, default='', help_text="Why this check-in was flagged (e.g., 'Accuracy 150m exceeds 50m threshold').", max_length=200),
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcheckin',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Officer who reviewed and cleared/flagged this check-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalGeoTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tag_code', models.CharField(db_index=True, editable=False, help_text='Unique human-readable + QR-scannable code, e.g. GT-2026-00456', max_length=30)),
                ('tag_type', models.CharField(choices=[('EAR_TAG', 'Ear Tag'), ('LEG_BAND', 'Leg Band'), ('QR_ONLY', 'QR Only'), ('GPS_COLLAR', 'GPS Collar')], default='EAR_TAG', max_length=15)),
                ('date_tagged', models.DateField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='False if tag is retired (lost, animal deceased, etc.).')),
                ('last_checkin', models.DateTimeField(blank=True, help_text='Timestamp of most recent LocationCheckIn for any custodianship under this tag.', null=True)),
                ('last_device_ping', models.DateTimeField(blank=True, help_text='Last ping from GPS device — separate from checkin to detect device failures.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, help_text='The animal this tag is attached to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='livestock.animal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replacement_of', models.ForeignKey(blank=True, db_constraint=False, help_text='If this is a replacement tag, link to the old tag for lineage continuity.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geotagging.geotag')),
                ('tagged_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical geo tag',
                'verbose_name_plural': 'historical geo tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
